[package]
name = "SketchyFlightDataRecorder"
authors = ["Ryan Kerr <ryan@rykr.ca>"]
version = "0.1.0"
edition = "2021"

[dependencies]
simconnect = "0.1.3"
sqlite = "0.26.0"
chrono = "0.4.0"
winapi = { version = "0.3.9", features = ["profileapi", "winbase"] }
